ecommerce/ecommerce/urls.py
from django.conf.urls import url
from django.contrib import admin
from user_model.views import user_signup, user_login, activate, user_home,password_reset, activate_password, password_reset_new
from products.views import home, search
from cart.views import view, cart_update
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register_user/', user_signup, name='user_signup'),
    url(r'^login_user/', user_login, name='user_login'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'^activate_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_password, name='activate_password'),
    url(r'^home/', user_home , name='user_home'),
    url(r'^$', home , name='home'),
    url(r'^search/', search, name='searchproduct'),
    url(r'^cart/(?P<slug>[\w-]+)/$', cart_update, name='cart_update'),
    url(r'^cart/', view, name='view'),
    url(r'^password_reset/', password_reset , name='password_reset'),
    url(r'^password_reset_new/', password_reset_new, name='password_reset_new'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=False)
    #price = models.DecimalField(decimal_places=2, max_digits=10, default=19.99)
    slug = models.SlugField(unique=True)
    #Image = models.FileField(upload_to='products/images/', null= True)
    #timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    #active = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title


class product_Image(models.Model):
    Product = models.ForeignKey(product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/', blank=True)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    #active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.Product.title


class product_price(models.Model):
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    product_Image = models.ForeignKey(product_Image, on_delete=models.CASCADE)
    #product_offer = models.ForeignKey(product_discount)
    # ye jo bhii aayegsaa ye approve loma se aayegsaa
    mrp = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    lastupdated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return self.product.title


class product_discount(models.Model):
    # yaha discount loma manually btaaa dega
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    Offer_in_percentage = models.IntegerField(default=0.00)
    lastupdated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return self.product.title


# class Daily_price_list(models.Model):
#    price_list_date = models.DateField(auto_now_add=True)
#    price_list_time = models.DateTimeField(auto_now_add=True)
#    product = models.ForeignKey(product)
#    vendor_daily_id = models.ForeignKey(vendor_daily_PL)
# yaha offer and list toh upar foreign key se aaaa jaaaaynge
#   offer_price = models.FloatField(default=10.5)
#    list_price = models.IntegerField(default=0.00)
#   margin = models.FloatField(default=0.00)

#   total_available_quantity = models.FloatField(default=50.5)
#   rating = models.IntegerField(default=2.5)
#   #Total = models.FloatField(default=0.00) ('ye alag table hogi total ke liye')

#   def __unicode__(self):
#        return self.product.title

ecommerce/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import product
from django.shortcuts import render , HttpResponse

# Create your views here.


def home(request):
    products = product.objects.all()

    context = {
        "products": products
    }

    return render(request, 'products/home.html', context)


def search(request):
    try:
        q = request.GET.get('Keyword')
        print (q)
        #return HttpResponse(q)
        products = product.objects.filter(title__icontains=q)
        #print products
        #return HttpResponse(products)
        if products:
            context = {"products": products, "query": q}
        else:
            message = "Somethings wents wrong! please try something new"
            context = {"empty": True, 'message': message, "query": q}
        return render(request, 'products/searchresult.html', context)
    except:
        return HttpResponse("hey")


def detail(request, slug):
    #try:
        details = product.objects.get(slug=slug)
        context = {
            'details': details
        }
        return render(request, 'products/detail.html', context)

ecommerce/templates/products/cards.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cards</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Product Tiles</h1>

        <div class="row">
            <div class="col-md-4 col-sm-12">
                <div class="card border-dark">
                    <img class="card-img-top" src="/static/media/products/images/bglogin2.jpg" alt="Card image cap">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-5 col-md-5 ">
                                <span class="text-muted">M.R.P: <del> 66 </del></span>
                            </div>
                            <div class="col-sm-3 col-md-3  p-0">
                                <span class="text-darken-4"><i class="fas fa-rupee-sign"></i> 20(Kg)</span>
                            </div>
                            <div class="col-sm-4 col-md-4 text-left pr-1">
                                <span class="text-success">  69% OFF</span>
                            </div>
                        </div>
                        <div class="row mt-4 ml-1 mr-1">
                            <button id="addbtn" class="btn col-md-2 col-sm-2 btn-small btn-success mr-2"><i class="fas fa-plus"></i></button>
                            <button class="btn col-md-7 col-sm-8 btn-small btn-outline-primary">Add to Cart (<span id="cartqty">1</span>) </button> <button class="btn col-md-2 col-sm-2 btn-small btn-danger ml-2" id="subbtn"><i class="fas fa-minus"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .btn {
            transition: all 0.5s;
        }
        
        .btn:hover {
            transform: scale(1.05);
            transition: all 0.2s;
        }
        
        .card {
            transition: all 0.5s;
        }
        
        .card:hover {
            transition: all 0.2s;
            transform: scale(1.01);
        }
    </style>
    <script>
        console.log('hello');
        $('#addbtn').on('click', function() {
            items = parseInt(document.getElementById('cartqty').innerText);
            if (items <
                20) {
                items += 1;
            }
            $('#cartqty').html(items)
        });
        $('#subbtn').on('click', function() {
            items = parseInt(document.getElementById('cartqty').innerText);
            if (items > 1) {
                items -= 1;
            }
            $('#cartqty').html(items)
        });
    </script>

</body>

</html>

ecommerce/templates/products/home.html
{% extends 'products/base.html' %} {% load staticfiles %} {% block banner %}

<aside id="colorlib-hero">
    <div class="flexslider">
        <ul class="slides">
            <li style="background-image: url({% static 'images/mandi3.jpg' %})">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc text-danger">
                                    <h1 class="head-1">Fresh</h1>
                                    <h2 class="head-2">Vegetables</h2>
                                    <h2 class="head-3">At your doorsteps's</h2>
                                    <p class="category"><span>New trending shoes</span></p>
                                    <p><a href="#" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url({% static 'images/mandi2.jpg' %});">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 class="head-1">Huge</h1>
                                    <h2 class="head-2">Sale</h2>
                                    <h2 class="head-3"><strong class="font-weight-bold">50%</strong> Off</h2>
                                    <p class="category"><span>Big sale</span></p>
                                    <p><a href="#" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            <li style="background-image: url({% static 'images/mandi1.jpg' %});">
                <div class="overlay"></div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3 text-center slider-text">
                            <div class="slider-text-inner">
                                <div class="desc">
                                    <h1 class="head-1">New</h1>
                                    <h2 class="head-2">Arrival</h2>
                                    <h2 class="head-3">up to <strong class="font-weight-bold">30%</strong> off</h2>
                                    <p class="category"><span>Vegetables and Fruits</span></p>
                                    <p><a href="#" class="btn btn-primary">Shop Collection</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</aside>

{% endblock %} {% block search %}

<div class="form-group">
    <form role="search" action="/search/">
        <input type="search" name="Keyword" class="form-control search" style="display: none;position: absolute;" placeholder="Search">
        <button class="btn-search btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
    </form>
</div>

{% endblock %} {% block line %}

<div class="colorlib-intro">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2 class="intro">We at Sabji Wala's deliver the best to our customers</h2>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block body %} {% load staticfiles %}
<div class="container mt-4 w-75">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 col-sm-12 col-12">
            <div class="card border-dark mb-4" style="width:100%;">
                {% for item in product.product_image_set.all %}
                <img class="card-img-top" style="height:250px;" src="{{ MEDIA_URL }}{{ item.image }}" alt="Card image cap"> {% endfor %}
                <div class="card-body">

                    <div class="row">

                        <div class="col text-center p-0">

                            <span class="text-darken-4"><h6>{{ product.title }}</h6></span>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col">
                            {% for item in product.product_price_set.all %}
                            <span class="text-muted">M.R.P: <del> {{item.mrp}} </del></span> {% endfor %}
                        </div>
                        <div class="col text-right p-0">
                            {% for item in product.product_price_set.all %}
                            <span class="text-darken-4"><i class="fas fa-rupee-sign"></i> {{ item.price }}(Kg)</span> {% endfor %}
                        </div>
                        <div class="col text-left pr-1">
                            {% for item in product.product_discount_set.all %}
                            <span class="text-success"> {{ item.Offer_in_percentage }}% OFF</span> {% endfor %}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <button id="addbtn" class="btn col-2 btn-success" style="margin-left: 10px; margin-right:-10px;"><i
                                class="fa fa-plus" style="position: absolute;top:25%;right:25%;"></i></button>
                        <form method="GET" class="col ml-1 mr-1 " action="{% url 'cart_update' product.slug %}">
                            {% csrf_token %}
                            <input type="hidden" id="carth" name="carth">
                            <!--<input type="number" id="carth" name="qty">-->
                            <button class="btn   btn-outline-primary atc" style="padding-left:10px; width: 100%;" type="submit">Add to Cart (<span id="cartqty">1</span>)</button>
                        </form>
                        <button class="btn col-2  btn-danger " style=" margin-left:-10px;" id="subbtn"><i
                                class="fas fa-minus" style="position: absolute;top:25%;right:25%;"></i></button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>
    .btn {
        border-radius: 40px;
        transition: all 0.5s;
    }
    
    .btn:hover {
        transform: scale(1.05);
        transition: all 0.2s;
    }
    
    .card {
        transition: all 0.5s;
    }
    
    .card:hover {
        transition: all 0.2s;
        transform: scale(1.01);
    }
    
    @media screen and (min-width: 600px) and (max-width:1000px) {
        .atc {
            font-size: 10px;
        }
    }
    
    @media screen and (max-width: 550px) {
        .atc {
            font-size: 10px;
        }
    }
    
    @media screen and (max-width: 450px) {
        .col {}
    }
</style>
<script>
    console.log('hello');
    $('#addbtn').on('click', function() {
        items = parseInt(document.getElementById('cartqty').innerText);
        if (items <
            20) {
            items += 1;
        }
        $('#cartqty').html(items)
        $('#carth').html(items)
    });
    $('#subbtn').on('click', function() {
        items = parseInt(document.getElementById('cartqty').innerText);
        if (items > 1) {
            items -= 1;
        }
        $('#cartqty').html(items)
        $('#carth').html(items)
    });
</script>

{% endblock %}

ecommerce/templates/products/searchresult.html
{% extends 'products/base.html' %}
{% load staticfiles %}

{% block search %}

    <div class="form-group">
        <form method="POST" action="/search/">
            <input type="search" name="Keyword" class="form-control search" style="display: none;position: absolute;" placeholder="Search">
            <button class="btn-search btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
        </form>
    </div>

{% endblock %}


{% block body %} {% load staticfiles %}
<div class="container mt-4 w-75">
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 col-sm-12 col-12">
            <div class="card border-dark mb-4" style="width:100%;">
                {% for item in product.product_image_set.all %}
                    <img class="card-img-top" style="height:250px;" src="{{ MEDIA_URL }}{{ item.image }}" alt="Card image cap">
                {% endfor %}
                <div class="card-body">

                        <div class="row">
                                
                                <div class="col text-center p-0">
                                    
                                        <span class="text-darken-4"><h6>{{ product.title }}</h6></span>
                                </div>
                                
                        </div>

                    <div class="row">
                        <div class="col">
                            {% for item in product.product_price_set.all %}
                                <span class="text-muted">M.R.P: <del> {{item.mrp}} </del></span>
                            {% endfor %}
                        </div>
                        <div class="col text-right p-0">
                            {% for item in product.product_price_set.all %}
                                <span class="text-darken-4"><i class="fas fa-rupee-sign"></i> {{ item.price }}(Kg)</span>
                            {% endfor %}
                            </div>
                        <div class="col text-left pr-1">
                            {% for item in product.product_discount_set.all %}
                                <span class="text-success"> {{ item.Offer_in_percentage }}% OFF</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row mt-3">
                        <button id="addbtn" class="btn col-2 btn-success" style="margin-left: 10px; margin-right:-10px;"><i
                                class="fa fa-plus" style="position: absolute;top:25%;right:25%;"></i></button>
                        <div class="col-1 p-0" style="width: 10px !important;"></div>
                        <button class="btn col-6  btn-outline-primary atc" style="padding-left:10px;">Add to Cart (<span id="cartqty">1</span>)</button>
                        <div class="col-1 p-0"></div>
                        <button class="btn col-2  btn-danger " style=" margin-left:-10px;" id="subbtn"><i
                                class="fas fa-minus" style="position: absolute;top:25%;right:25%;"></i></button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>
    .btn {
        border-radius: 40px;
        transition: all 0.5s;
    }
    
    .btn:hover {
        transform: scale(1.05);
        transition: all 0.2s;
    }
    
    .card {
        transition: all 0.5s;
    }
    
    .card:hover {
        transition: all 0.2s;
        transform: scale(1.01);
    }
    
    @media screen and (min-width: 600px) and (max-width:1000px) {
        .atc {
            font-size: 10px;
        }
    }
    
    @media screen and (max-width: 550px) {
        .atc {
            font-size: 10px;
        }
    }
    
    @media screen and (max-width: 450px) {
        .col {
            padding: 0px;
        }
    }
</style>
<script>
    console.log('hello');
    $('#addbtn').on('click', function() {
        items = parseInt(document.getElementById('cartqty').innerText);
        if (items <
            20) {
            items += 1;
        }
        $('#cartqty').html(items)
    });
    $('#subbtn').on('click', function() {
        items = parseInt(document.getElementById('cartqty').innerText);
        if (items > 1) {
            items -= 1;
        }
        $('#cartqty').html(items)
    });
</script>

{% endblock %}